== Frequently-Asked Questions

== Playtesting FAQ

=== How do I build this thing?
Right now?  Manually.  Working on creating files to make it simpler, but for
now, these parts should suffice:

* http://www.printplaygames.com/product/die-cut-pieces-tiles-and-counters
** 22x 2.2" hex tiles for sectors (two sheets from the above link).
* http://www.printplaygames.com/product/acrylic-gem-10mm
** Acrylic gems to represent liquid currency.
** 40x red $5s and 60x white $1s should be enough.
** The important thing is to have liquidity -- poker chips would also work
   fine.
* https://www.printplaygames.com/product/25mm-x-7mm-wood-discs
** Six disks each in black, blue, white, and red.
* http://www.printplaygames.com/product/blank-cards
** 52 poker-sized cards for constructing your deck.
** I’ve been using sharpies to write card text with colored dots down the side.

=== [X] is broken!
Cards are not meant to be equally-powerful, and some are extremely situational.
Proper card evaluation is the cornerstone of good play.

=== Why is the starting player arbitrary?
We’ve not found any advantage nor disadvantage to being the starting player.
This is also why players start the same, aside from the cards dealt. 

=== Why start with nine gems?
Fewer gems makes early-game bidding much more risky, while more gems makes them
much more swingy.  This number is still being tuned.

=== Why start with three cards?
Primarily to give a new player something to latch onto.  An official variant is
to start with more money (probably somewhere around 16 gems) and no cards,
forcing the first move to be random exploration.  This causes the game to slow
down a bit, but also makes it more strategic.

=== Why can’t you encourage collapse?
Joshua O’M. suggested a way to modify preservation bids such that you can count
your bid against preservation, instead of for it.  I don’t think this is worth
the complexity, but perhaps could be exposed by a card.

=== Why do you recover your discard at the start of your turn?
To ensure the other players have a chance to auction off your last card played.

=== Why does the game end with the last disk placement?
Primarily to allow players to control the speed of the game.  Several other
endgames have been suggested, but Sage says it best:

> I think the temptation is to make endgame 'The End of History' where this
> empire is different than all those that came before it, and the end board
> state is the end of the story.
>
> But this is The Rise and Fall of Galactic Empires. There is no end to the
> 'story' of it, there will always be another empire. So ending at some
> arbitrary point is the only ending, really. -- Sage LaTorra
