== Frequently-Asked Questions

=== What if I use Crusade of the Sun to take the last disk?

You must place all the taken disks on your turn, and then the game ends.

== Playtesting

=== How do I build this thing?
Right now?  Manually.  Working on creating files to make it simpler, but for
now, these parts should suffice:

- http://www.printplaygames.com/product/die-cut-pieces-tiles-and-counters
  - 20x 1.5” hex tiles for sectors (one sheet from the above link).
  - Value distribution: 1 at 4-value, 2 at 3-value, 5 at 2-value, 7 at 1-value,
    5 at 0-value.
- http://www.printplaygames.com/product/acrylic-gem-10mm
  - Acrylic gems to represent liquid currency.
  - 30x red $5s and 30x white $1s should be enough.
  - The important thing is to have liquidity -- poker chips would also work
    fine.
- http://www.printplaygames.com/product/15mm-wood-discs
  - Six disks each in black, blue, white, and red.
- http://www.printplaygames.com/product/blank-cards
  - 52 poker-sized cards for constructing your deck.
  - I’ve been using sharpies to write card text with colored dots down the
    side.

=== [X] is broken!
Remember that you can auction cards from the top of anyone’s discard pile.
Cards are not meant to be equally-powerful, and some are extremely situational.
Proper card evaluation is the cornerstone of good play.

== Suggestions

=== Why is the starting player arbitrary?
We’ve not found any advantage nor disadvantage to being the starting player.
This is also why players start the same, aside from the cards dealt. 

=== Why start with nine gems?
Fewer gems makes early-game auctions and preservations much more risky, while
more gems makes them much more swingy.  This number is still being tuned.

=== Why start with three cards?
Primarily to give a new player something to latch onto.  An official variant is
to start with more money (probably somewhere around 16 gems) and no cards,
forcing the first move to be an auction.  This causes the game to slow down a
bit, but also makes it more strategic.

=== Why is the market four cards?
Arbitrary.  It must be more than one, to provide a choice.  Some cards count
things in the market, so it can’t be more than four or five, to restrict the
high-end of those.  Three might be do-able, but four seems to work well.

=== Why use simultaneous auctions?
For game speed.  The high-bidder pays for simplicity, and to keep the game’s
economy running.  Alternate auctions have been suggested, but they either
lengthen the game, reduce the expected bidding amounts, or reduce the expected
profit for the active player.

=== Why can’t you encourage collapse?
Joshua O’M. suggested a way to modify preservation bids such that you can count
your bid against preservation, instead of for it.  I don’t think this is worth
the complexity, but perhaps could be exposed by a card.

=== Why do you recover your discard at the start of your turn?
To ensure the other players have a chance to auction off your last card played.

=== How do I survive preservation bids until I can sell my cards?
Joe suggests a "commission" rules change: All players may sell a card when one
person sells.

When the active player sells a card all other players have an opportunity to
also sell a card of the same color. The active player takes a 1 gem commission
from each opponent that sells this way. (Alternatively take 1 gem from the
bank)

=== Why does the game end with the last disk placement?
Primarily to allow players to control the speed of the game.  Several other
endgames have been suggested, but Sage says it best:

> I think the temptation is to make endgame 'The End of History' where this
> empire is different than all those that came before it, and the end board
> state is the end of the story.
>
> But this is The Rise and Fall of Galactic Empires. There is no end to the
> 'story' of it, there will always be another empire. So ending at some
> arbitrary point is the only ending, really. -- Sage LaTorra
