== Frequently-Asked Questions

=== Known Bugs

==== [RC1] What if my opening hand is worthless?
Place those colors out and sell it as soon as you can.  We’re considering
several possible fixes here, including:

- A mulligan rule.
- Drafting initial hands.
- Starting with no cards but more money.

==== [RC1] What if nothing adds gems to sectors?
If none of these cards come out, a bunch of cards are worthless.  I’m
considering a change that would make them more consistently useful, make
preservation more powerful for the bidders and simpler to resolve, and make
some of the attack cards more interesting in play:

- Preservation bids are placed on stacks when revealed.

One gem saves a stack.  This means the bidders save their choice of stack.  It
means that in larger player counts, multiple consecutive sales hurt less.  It
means selling could make sectors more powerful, which seems thematically odd,
but represents outside investment helping the faction in control (when a new
disk is added, the gem moves to the sector).  If another sale happens, gems
already atop stacks count as auto-bids, perhaps.  Cards that take gems from
sectors can be used to de-shield stacks.

==== [RC1] What if I have no way to get regular income?
Sell cards and make the other players pay you to hold onto their own cards.
The big possible fixes for this one could also possibly fix another few worries
I have:

- When you use a card to place a disk, gain gems equal to the value of that
  sector.
- When you place a new sector tile, gain gems equal to the value of that
  sector.
- First solution + when you turn over a new sector, also reveal the top event
  card and perform its effect.

==== [RC1] What keeps the game from stalling out?
Good question.  Disk placement makes colors worth more, but if a particular
color benefits everyone equally, there’s no reason to use a turn placing it.
Normally the colors are unbalanced enough for someone to decide it’s worth it,
but that’s a big risk.  The above fixes (income when placing disks) is what I’m
thinking, but several others have been suggested:

- Whenever you play a card, place a disk and take the event (instead of just
  one).
- Always begin your turn by placing a disk.  (Makes a strict clock.)
- Come up with an alternate endgame (perhaps an empty galaxy).

==== [RC1] Can my Zele Research Labs retrieve a card I sold?
As written, yes.  I didn’t mean for this to be possible, but such is life.
I’ll likely change it to be opponents’ cards only, but lets play it as it lies
for RC1.

==== [RC1] What’s up with Crusade of the Sun?
This card is horribly-written, I apologize.  It’s meant to allow you to store
up disks for a massive one-turn invasion.  If you have suggestions for how to
write it in the future, let me know.  For now, treat the text this way:

.Crusade of the Sun
====
Place a disk on this card.  Each turn this card is atop your discard, place
another disk of the same color on it.  When it’s no longer atop your discard,
place all these disks on the map (as usual for disk placement).
====

==== [RC1] The Ru-Shou Dam is buh-roken!
See [G+](https://plus.google.com/+AdamBlinkinsop/posts/DhRcWgw2NT5) for ongoing
discussion.  It may be changed or removed in RC2.

=== Playtesting

==== How do I build this thing?
Right now?  Manually.  Working on creating files to make it simpler, but for
now, these parts should suffice:

- http://www.printplaygames.com/product/die-cut-pieces-tiles-and-counters
  - 20x 1.5” hex tiles for sectors (one sheet from the above link).
  - Value distribution: 1 at 4-value, 2 at 3-value, 5 at 2-value, 7 at 1-value,
    5 at 0-value.
- http://www.printplaygames.com/product/acrylic-gem-10mm
  - Acrylic gems to represent liquid currency.
  - 30x red $5s and 30x white $1s should be enough.
  - The important thing is to have liquidity -- poker chips would also work
    fine.
- http://www.printplaygames.com/product/15mm-wood-discs
  - Six disks each in black, blue, white, and red.
- http://www.printplaygames.com/product/blank-cards
  - 52 poker-sized cards for constructing your deck.
  - I’ve been using sharpies to write card text with colored dots down the
    side.

==== [X] is broken!
Remember that you can auction cards from the top of anyone’s discard pile.
Cards are not meant to be equally-powerful, and some are extremely situational.
Proper card evaluation is the cornerstone of good play.

=== Suggestions

==== Why is the starting player arbitrary?
We’ve not found any advantage nor disadvantage to being the starting player.
This is also why players start the same, aside from the cards dealt. 

==== Why start with nine gems?
Fewer gems makes early-game auctions and preservations much more risky, while
more gems makes them much more swingy.  This number is still being tuned.

==== Why start with three cards?
Primarily to give a new player something to latch onto.  An official variant is
to start with more money (probably somewhere around 16 gems) and no cards,
forcing the first move to be an auction.  This causes the game to slow down a
bit, but also makes it more strategic.

==== Why is the market four cards?
Arbitrary.  It must be more than one, to provide a choice.  Some cards count
things in the market, so it can’t be more than four or five, to restrict the
high-end of those.  Three might be do-able, but four seems to work well.

==== Why use simultaneous auctions?
For game speed.  The high-bidder pays for simplicity, and to keep the game’s
economy running.  Alternate auctions have been suggested, but they either
lengthen the game, reduce the expected bidding amounts, or reduce the expected
profit for the active player.

==== Why can’t you encourage collapse?
Joshua O’M. suggested a way to modify preservation bids such that you can count
your bid against preservation, instead of for it.  I don’t think this is worth
the complexity, but perhaps could be exposed by a card.

==== Why do you recover your discard at the start of your turn?
To ensure the other players have a chance to auction off your last card played.

==== How do I survive preservation bids until I can sell my cards?
Joe suggests a "commission" rules change: All players may sell a card when one
person sells.

When the active player sells a card all other players have an opportunity to
also sell a card of the same color. The active player takes a 1 gem commission
from each opponent that sells this way. (Alternatively take 1 gem from the
bank)

==== Why does the game end with the last disk placement?
Primarily to allow players to control the speed of the game.  Several other
endgames have been suggested, but Sage says it best:

[quote, Sage LaTorra]
____
I think the temptation is to make endgame 'The End of History' where this
empire is different than all those that came before it, and the end board state
is the end of the story.

But this is The Rise and Fall of Galactic Empires. There is no end to the
'story' of it, there will always be another empire. So ending at some arbitrary
point is the only ending, really.
____
