= The Rise and Fall of Galactic Empires
Adam Blinkinsop <http://google.com/+AdamBlinkinsop>
0.21-{revision}, {docdate}
:toc: left
:homepage: http://blinks.github.io/ozymandias/

[verse, Percy Bysshe Shelley, Ozymandias]
____
And on the pedestal these words appear:
'My name is Ozymandias, king of kings:
Look on my works, ye Mighty, and despair!'
Nothing beside remains. Round the decay
Of that colossal wreck, boundless and bare
The lone and level sands stretch far away.
____

== Objective
*Rise* is played in turns.  Each turn, the active player chooses and resolves
one of three different actions.  Everyone then activates cards matching that
action.

You must influence and take advantage of shifting faction control to profit;
eliminating cards that are worthless while cycling cards that still have use.

*The winner is the player who holds the most valuable cards at the end of the game.*

== Components
|===
|resources    |?? @ 1 and ?? @ 5.
|54 cards     |13 each in four factions.
|24 disks     |6 each in four factions.
|sector tiles |with a value from one to three.
|===

== Setup
Shuffle the *sector tiles* and *deck of cards* separately.  Set the *resources*
and *disks* to one side, in common pools.

Give each player three cards, face-up to make their initial plots, and draw and
place three sectors (in a triangle) to make the initial map.

== Play
Rise is played over a number of turns.  On each turn, the active player chooses
an action, then each player may resolve at most one of their matching active
cards.

NOTE: I'm considering allowing players to discard in response to an action, to
set up their active cards.

At the beginning of your turn, you may recover one of your discard piles.

=== Explore (draw new cards)
. [Optional] Draw and place a sector.
.. Discard the oldest X cards from the horizon, where X is the sector's stability.
.. Refresh the horizon with new cards from the deck.
. Take a card.
. Each player may resolve one exploration effect.

=== Conquer (control sectors)
. Play one or more cards, either all different colors or all the same color.
.. You must place each card on a different pile.
.. You must place on existing piles before creating new piles.
. For each card, take a matching disk.
.. You must take unplaced disks before living disks.
.. You must take conquered disks before ruling disks.
.. You may not take dead disks.
. Place each disk on the corner of a sector.
.. You may place on an existing stack of disks.
.. You may not place on a stack that already contains the disk's color.
.. You may not create a stack only one edge away from another stack. (Catan)
. Each player may resolve one conquer effect.

=== Reap (destroy empires)
. Destroy one or more ruling disks.
.. Each one costs its stability for each matching active or horizon card.
.. You may destroy a matching card from your hand to ignore one matching card.
. Place each destroyed disk next to a non-matching dead pile, and take a card
  from that pile, if possible.
. Each player may resolve one reap effect.

A disk's stability is the sum of the stabilities of all sectors it rules.

== The End
The game ends _at the end of the turn_ in which one of the following is true:

* No cards remain in the deck or horizon.
* No sectors remain in the pile.
* No disks remain in the pool.
* All disks of one color are dead.

=== Scoring
Count up the value of each color, which is the sum of the following:

* 2 x the number of its ruling disks.
* 1 x the number of disks next to its dead pile.

Cards are each worth their color's value.  Add up each player's points.  The
player with the most is the winner.

include::cards.asciidoc[]

'''
include::faq.asciidoc[]
