= The Rise and Fall of Galactic Empires
Adam Blinkinsop <http://google.com/+AdamBlinkinsop>
0.4-{revision}, {docdate}
:toc: left
:homepage: http://blinks.github.io/ozymandias/

A game for two to four immortals, plays in about 500 millenia (an hour).

== Introduction

[verse, Percy Bysshe Shelley. Ozymandias]
____
And on the pedestal these words appear:
'My name is Ozymandias, king of kings:
Look on my works, ye Mighty, and despair!'
Nothing beside remains. Round the decay
Of that colossal wreck, boundless and bare
The lone and level sands stretch far away.
____

_Rise_ is a 2- to 4-player board game depicting the life cycle of space-faring
civilizations over millennia.  Each player takes the role of a powerful
immortal seeking to have the most influence over humanity, whether benevolent
investment or malevolent destruction.

=== Components
A complete set of _Rise_ includes:

* 22 hexagonal sector tiles.
* A deck of 52 cards, in four different colors.
* 24 black, blue, red, and white wooden disks.
* Influence gems in white (1s) and red (5s).
* This rule book.

=== The Galaxy
Sector tiles depict an enormous expanse of space.  This expanse is reduced down
to a natural resource value of 0, 1, 2, 3, or 4.  A sector's value may be
further augmented by influence gems placed on the tile.

IMPORTANT: The *value* of a sector is always the sum of the natural resources
and the invested influence.

Sectors are kept face-down, and drawn when a player explores a new region of
space.  The location of a sector is always chosen before that sector is
revealed.

NOTE: Face-up sectors are *explored*.  *Unexplored* sectors are any sectors
that (1) don't yet have a tile and (2) are adjacent to explored sectors.

=== Civilizations
The wooden disks represent the various archetypical civilizations (civs).  At
the beginning of the game, these have yet to rise to any real place in the
galaxy, and all sit in a pool at the side of the table.  Players will place
them on sector tiles to expand their influence, and they might collapse into
obscurity whenever a player harvests a card of their color.

Each sector tile holds a single civ stack.  Only the top civ is active,
benefiting from the value of the sector.  The stack serves as a historical
record of expansion in the sector.  A sector with no civs is *empty*.

When a civilization disk is destroyed, it goes to the active player.  At the
end of the game, these count for influence equal to the harvest value of their
color.  Some card effects also spend these dead disks, returning them to the
common pool.

A game of _Rise_ lasts only as long as there are civs in the common pool.  At
the end of the turn where the last civ is placed, the game ends.

=== Cards
The deck of cards represents archetypical historical events, the kind that get
referenced in speech enough to become a stand-in for anything similar.  Each
card has a color of civilization that it influences, a title, and some rules
text.

There are four major types of cards:

NOTE: These should be given more evocative names.

* *Actions* happen when the card is played or revealed for exploration.
* *Triggered effects* happen when the specified trigger occurs.
* *Timed effects* happen each turn, as long as the card is active.
* *Static effects* continuously apply as long the card is active.

NOTE: Static and timed effects will potentially be laid out landscape, while
actions and triggered effects will be laid out in portrait.

At the beginning of the game, each player has three cards in their hand and the
market has three cards face-up on the side of the playing area.

Players will place cards on their own discard piles, recovering their discard
in its entirety when their hand is empty.  The top card of each player's
discard pile is considered "active".

TIP: If you're going to spend several turns auctioning or harvesting, get a
useful active effect out first. 

Players will place cards in the market up for auction to expand the range of
powers their immortal avatars wield. Purchased cards will be placed in the
high-bidder's hand.  When harvested, cards will be buried on the bottom of the
deck.

== Set Up

. Shuffle the sector tiles and draw one to place in the middle of the playing
  area to make the initial explored sector.
. Shuffle the deck and place three face-up cards to the side of the playing
  area to make the initial market.
. Deal three more cards to each player to make their initial hands.  Players
  may look at their hands.  One time only, players may bury any number of
  cards and draw replacements from the deck.  If any player chooses this
  option, the deck should be reshuffled.
. Give nine influence to each player (four white gems and one red gem) to make
  their initial banks.  Place the rest near the market.
. Place the disks in a common pool reachable by all players.

== Sequence of Play

A turn in _Rise_ consists of a single action:

* Play a card from your hand to *expand*.
* Play a card from your hand for its *event*.
* *Auction* a market card or any player's active card.
* *Harvest* a card from your hand for its influence value.

Cards that trigger "at start/end of turn" happen before/after your action,
respectively.  If you have no cards in your hand and want to do anything but
auction, pick up your discard pile after triggering any "at start of turn"
active effect.

After "at end of turn" actions trigger:

* If no civs are left in the pool, end the game.
* If the market has less than three cards, add enough cards from the deck to
  refill it. 

=== Expand
Expansion adds civs to the galaxy and gives you influence to spend.  If you
expand into a new sector, you also take an exploration effect.

. Play a card.  This card determines what color you expand with.  This card
  isn't placed on your discard pile until the end of the action.
. Place a disk of that color.
** If that color is currently active in the galaxy, you may place in any sector
   adjacent to where it's active.
** Otherwise, you may place in any empty or unexplored sector.
. If you placed in an unexplored sector, explore.
.. Draw a new sector and place it under the disk.
.. Reveal the top card of the deck and -- if it has an action -- execute it.
. Gain influence gems equal to the sector's value.
. Discard your played card.  It is now active.

NOTE: If no disks of your card's color remain, you may expand without placing a
disk.  However, you don't gain influence nor explore.  This is generally done
only when the event has no action or you don't want the event's action.

=== Event
Events provide powerful and widely-varied effects, but seldom any income.  Use
them wisely.

. Play a card with an action.  This card isn't placed on your discard pile
  until the end of the action.
. Read that action and do what it says.
. Discard your played card.  It is now active.

NOTE: The current card layout places action rules text above a horizontal line,
and triggered rules text below a horizontal line.  As a general rule, if a card
sounds like an action, it probably is.

=== Auction
Auctions are the primary way of getting new cards into players' hands.  If you
auction from the market, you'll either get the card or some influence.
Auctioning someone's active card is sometimes the only way to deal with a
powerful effect.

. Choose a card to auction, placing it in front of you, facing out.
. Hide your influence gems and take zero or more into your hand as your bid.
. When you've chosen your bid, hold your fist over the playing area.
. Once all players have chosen, reveal your bids by opening your fists.
. The high-bidder wins the card, which goes into their hand.
** It goes into their hand even if it was formerly their active card.
** The active player breaks ties.
. The high-bidder pays their bid as follows, everyone else keeps their bid.
** A market card: pay the active player; the active player pays the bank.
** An active card: pay the former owner; the former owner pays the active
   player.

=== Harvest
When a civilization has reached its peak, harvesting that color of cards is the
best way to lock in the influence it provides.  A harvest also forces players
to pay influence to support the color, should they care about its value.

. Choose a card to harvest, placing it in front of you, turned sideways.  This
  card determines what color you get value from.
. Sum up the value of each sector where that color is active.
. Gain that much influence from the bank.
. *Preservation*
.. Hide your influence gems and take zero or more into your hand as your bid.
.. When you've chosen your bid, hold your fist over the playing area.
.. Once all players have chosen, reveal your bids by opening your fists.
.. Sum the total influence bid.  Each influence preserves one sector controlled
   by the harvested color, starting with the highest value sector and
   continuing down.
*** If there is not enough influence to preserve all that color's sectors,
    pay all the influence to the bank and destroy that color's active civ in
    sectors not preserved.  The active player breaks ties.  Give these
    destroyed disks to the active player.
*** If there is more than enough, pay the influence used to preserve to the
    bank and place the rest in any one sector controlled by the harvested
    color.  (The active player chooses.)
. Trigger any "when harvested" effects.
. Bury the harvested card on the bottom of the deck.

== Scoring and Victory

The object of the game is to hold influence.  Influence gems are easier to
spend and more stable, but cannot grow in value by themselves.  Cards provide
effects and opportunities to expand, but are volatile and difficult to spend.

At the end of the game, each player scores influence in three ways:

. Influence gems are worth their value.
. Cards are worth their color's harvested value.
. Dead civs are worth their color's harvested value.

NOTE: A scoring sheet with a column for each player and rows for each color (as
well as gems) is recommended for play-testing.

The player with the highest total wins.  In the case of a tie, the player with
the most influence gems wins.  If still tied, the player who would next have
taken their turn wins.

== Tournament Play

NOTE: These rules are optional, and are not required for 'friendly' play.  They
are simply offered as guidelines on conducting _Rise_ as a competitive game.

. Play with each player's bank of influence gems kept public (except for right
  before a bid).
. After the exploration effect is taken, keep that card revealed on top of the
  deck instead of turning it back over.
. Consider using a chess clock or some other timer to restrict calculation
  during play.

== The Empty Hand Variant

[.lead]
Start the game with 0 cards and 18 gems, instead of 3 cards and 9 gems.

This eliminates hidden information in the early game, and makes card evaluation
much more important.

'''

include::faq.asciidoc[]

include::cards.asciidoc[]
