= A History of Preascendant Humanity
Adam Blinkinsop <http://google.com/+AdamBlinkinsop>
1.0 RC1
:toc:

A game for two to four players, plays in about an hour.

[verse, Percy Bysshe Shelley. Ozymandias]
____
And on the pedestal these words appear:
'My name is Ozymandias, king of kings:
Look on my works, ye Mighty, and despair!'
Nothing beside remains. Round the decay
Of that colossal wreck, boundless and bare
The lone and level sands stretch far away.
____

== Overview
You are immortal puppet-masters, managing a coalition of factions to ensure
they control the galaxy through exploration, expansion, exploitation, and
extermination of rival factions.  Not even the most powerful faction survives
forever, and the loyalty of currently-weak factions is cheap.  You must take
the long view.

== Objective
Have the most influence at the end of the game.

Colors are worth influence equal to the value of all sectors they control.
Each card is worth influence equal to its color.

.Card influence.
====
I have two red cards.

Red controls three hexes with values two, one, and zero, so my cards are worth
three influence each: six influence total.
====

== Components
- This rulebook.
- A deck of event cards.
- A collection of influence tokens.
- 24 control disks, six in each of four colors.
- 20 hexagonal sector tiles.

== Setup
- Deal each player three cards and nine influence.
- Draw four cards to make the *market*.
- Decide which player is closest to immortality.  That player starts.

TODO: A diagram of play.

== Play
Play proceeds in turns.  At the beginning of your turn, if you have no cards
left, recover your discard pile.  Take one of the following actions:

- Sow a market card or any active card.
- Reap a card from your hand for influence.
- Play a card for expansion.
- Play a card for its event.

If there are no disks left in the pool at the end of your turn, *the game
ends.*

=== Sow
Put a card up for auction; place it in front of you during this process.

1. Everyone secretly bids influence and simultaneously reveals their bids.
2. The high bidder takes the card, the active player breaks all ties.
3. If the active player wins, they pay the card's former owner (which is the
   bank in case of a market card).  Otherwise, the high bidder pays the active
   player.

=== Reap
Sell a card for influence; place it in front of you during this process.

1. Determine the value of its color by counting up sector values.
2. Collect that much influence from the bank.
3. Bid for preservation of that color.
4. Place the reaped card on the bottom of the market deck.

==== Preservation and Collapse

1. Everyone secretly bids influence and simultaneously reveals their bids.
2. Counter-clockwise from the active player, each bidder chooses which sectors
   to save.  Players can choose one sector for each influence they bid.
3. In sectors not saved, destroy the top disk.

.Preservation of blue
====
In a two-player game, blue controls two sectors.

Alice bids nothing and Bob bids one influence to preserve blue.

Bob decides which sector to save.  The other sector's top disk is destroyed.
====

=== Expand
Play a card to place a disk.

1. Put the card on your discard pile.  It's now active.
2. Take a disk of its color and place it on the map adjacent to another sector
   controlled by its color.  If no such sectors exist, place the disk in any
   unoccupied sector.
   - If you placed in an unexplored sector, draw a new sector to put there.
3. Collect influence equal to the sector's value.
4. If you drew a new sector, reveal and execute the top card of the event deck.
   (Leave it on top afterwards.)

=== Event
Play a card to execute its event.

1. Put the card on your discard pile.  It's now active.
2. Follow its instructions.

== Frequently-Asked Questions

=== Known Bugs

==== [RC1] What if my opening hand is worthless?
Place those colors out and sell it as soon as you can.  We’re considering
several possible fixes here, including:

- A mulligan rule.
- Drafting initial hands.
- Starting with no cards but more money.

==== [RC1] What if nothing adds gems to sectors?
If none of these cards come out, a bunch of cards are worthless.  I’m
considering a change that would make them more consistently useful, make
preservation more powerful for the bidders and simpler to resolve, and make
some of the attack cards more interesting in play:

- Preservation bids are placed on stacks when revealed.

One gem saves a stack.  This means the bidders save their choice of stack.  It
means that in larger player counts, multiple consecutive sales hurt less.  It
means selling could make sectors more powerful, which seems thematically odd,
but represents outside investment helping the faction in control (when a new
disk is added, the gem moves to the sector).  If another sale happens, gems
already atop stacks count as auto-bids, perhaps.  Cards that take gems from
sectors can be used to de-shield stacks.

==== [RC1] What if I have no way to get regular income?
Sell cards and make the other players pay you to hold onto their own cards.
The big possible fixes for this one could also possibly fix another few worries
I have:

- When you use a card to place a disk, gain gems equal to the value of that
  sector.
- When you place a new sector tile, gain gems equal to the value of that
  sector.
- First solution + when you turn over a new sector, also reveal the top event
  card and perform its effect.

==== [RC1] What keeps the game from stalling out?
Good question.  Disk placement makes colors worth more, but if a particular
color benefits everyone equally, there’s no reason to use a turn placing it.
Normally the colors are unbalanced enough for someone to decide it’s worth it,
but that’s a big risk.  The above fixes (income when placing disks) is what I’m
thinking, but several others have been suggested:

- Whenever you play a card, place a disk and take the event (instead of just
  one).
- Always begin your turn by placing a disk.  (Makes a strict clock.)
- Come up with an alternate endgame (perhaps an empty galaxy).

==== [RC1] Can my Zele Research Labs retrieve a card I sold?
As written, yes.  I didn’t mean for this to be possible, but such is life.
I’ll likely change it to be opponents’ cards only, but lets play it as it lies
for RC1.

==== [RC1] What’s up with Crusade of the Sun?
This card is horribly-written, I apologize.  It’s meant to allow you to store
up disks for a massive one-turn invasion.  If you have suggestions for how to
write it in the future, let me know.  For now, treat the text this way:

.Crusade of the Sun
====
Place a disk on this card.  Each turn this card is atop your discard, place
another disk of the same color on it.  When it’s no longer atop your discard,
place all these disks on the map (as usual for disk placement).
====

==== [RC1] The Ru-Shou Dam is buh-roken!
See [G+](https://plus.google.com/+AdamBlinkinsop/posts/DhRcWgw2NT5) for ongoing
discussion.  It may be changed or removed in RC2.

=== Playtesting

==== How do I build this thing?
Right now?  Manually.  Working on creating files to make it simpler, but for
now, these parts should suffice:

- http://www.printplaygames.com/product/die-cut-pieces-tiles-and-counters
  - 20x 1.5” hex tiles for sectors (one sheet from the above link).  TODO: Art.
  - Value distribution: 1 at 4-value, 2 at 3-value, 5 at 2-value, 7 at 1-value,
    5 at 0-value.
- http://www.printplaygames.com/product/acrylic-gem-10mm
  - Acrylic gems to represent liquid currency.
  - 30x red $5s and 30x white $1s should be enough.
  - The important thing is to have liquidity -- poker chips would also work
    fine.
- http://www.printplaygames.com/product/15mm-wood-discs
  - Six disks each in black, blue, white, and red.
- http://www.printplaygames.com/product/blank-cards
  - 52 poker-sized cards for constructing your deck.
  - I’ve been using sharpies to write card text with colored dots down the
    side.

==== [X] is broken!
Remember that you can auction cards from the top of anyone’s discard pile.
Cards are not meant to be equally-powerful, and some are extremely situational.
Proper card evaluation is the cornerstone of good play.

=== Suggestions

==== Why is the starting player arbitrary?
We’ve not found any advantage nor disadvantage to being the starting player.
This is also why players start the same, aside from the cards dealt. 

==== Why start with nine gems?
Fewer gems makes early-game auctions and preservations much more risky, while
more gems makes them much more swingy.  This number is still being tuned.

==== Why start with three cards?
Primarily to give a new player something to latch onto.  An official variant is
to start with more money (probably somewhere around 16 gems) and no cards,
forcing the first move to be an auction.  This causes the game to slow down a
bit, but also makes it more strategic.

==== Why is the market four cards?
Arbitrary.  It must be more than one, to provide a choice.  Some cards count
things in the market, so it can’t be more than four or five, to restrict the
high-end of those.  Three might be do-able, but four seems to work well.

==== Why use simultaneous auctions?
For game speed.  The high-bidder pays for simplicity, and to keep the game’s
economy running.  Alternate auctions have been suggested, but they either
lengthen the game, reduce the expected bidding amounts, or reduce the expected
profit for the active player.

==== Why can’t you encourage collapse?
Joshua O’M. suggested a way to modify preservation bids such that you can count
your bid against preservation, instead of for it.  I don’t think this is worth
the complexity, but perhaps could be exposed by a card.

==== Why do you recover your discard at the start of your turn?
To ensure the other players have a chance to auction off your last card played.

==== How do I survive preservation bids until I can sell my cards?
Joe suggests a "commission" rules change: All players may sell a card when one
person sells.

When the active player sells a card all other players have an opportunity to
also sell a card of the same color. The active player takes a 1 gem commission
from each opponent that sells this way. (Alternatively take 1 gem from the
bank)

==== Why does the game end with the last disk placement?
Primarily to allow players to control the speed of the game.  Several other
endgames have been suggested, but Sage says it best:

[quote, Sage LaTorra]
____
I think the temptation is to make endgame 'The End of History' where this
empire is different than all those that came before it, and the end board state
is the end of the story.

But this is The Rise and Fall of Galactic Empires. There is no end to the
'story' of it, there will always be another empire. So ending at some arbitrary
point is the only ending, really.
____

== Cards

[cols="^1,2,6", options="header"]
.Manifest
|===
|ID  |Name | Event
|R01 |Fires at Night
|Pay up to 3 gems.  Destroy that many top disks.
|R02 |Crusade of the Sun
|Take a disk. Choose one: retrieve this card or place all taken disks.
|R03 |Like a Torrent
|Take a gem from all sectors adjacent to red control.
|R04 |Blood from a Stone
|Take all gems from an unoccupied sector.
|R05 |Fall of Gethi E'Feri
|When you sell this card, destroy all controlling red disks.
|R06 |Berserkers of Grotl
|Gain a gem for each destroyed red disk.
|R07 |Thani Tribes
|Move all disks of one color to adjacent sectors.
|R08 |Cyri's Treachery
|Replace a card at random from an opponent's hand with this card.
|R09 |Revolution
|Move a disk to the top of its stack.
|R10 |Treasure Vaults
|Take all gems from a non-red sector.
|R11 |Robber Barons
|Destroy all non-red market cards.
|R12 |The Ru-Shou Dam
|Bid for preservation of all colors. You gain opponents' bids.
|R13 |Wreckage of the Xyri
|While atop your discard: New sectors may not be drawn.

|W01 |Futures Market
|Gain one gem for each white card in the market.
|W02 |The New Economy
|Place 3 gems on one or more market cards.
|W03 |Critical Mass
|Bid for preservation of white.  Place all bids in one sector.
|W04 |Maengali's Discovery
|Place three gems in a sector.
|W05 |The Crystalline City
|Gain a gem for each color in a sector.
|W06 |Galactic Union
|When this card is purchased, gain a gem for each occupied sector.
|W07 |Unity is Strength
|Reveal your hand.  Gain a gem for each white card revealed.
|W08 |Chera's Tithe
|Gain a gem for each white-controlled sector.
|W09 |Zele Research Labs
|While atop your discard: Put sold cards in your hand.
|W10 |Thorwed's Gambit
|Auction the top two cards from the event deck as one lot.
|W11 |The City of Anten
|Move all gems in one sector to adjacent sectors.
|W12 |Shupa Vane Route
|Gain a gem for each unique color with control.
|W13 |Nyri Artifacts
|Auction all white cards in the market as one lot.

|B01 |Banii's Ritual
|Reveal the top event card and execute its event.
|B02 |Treaty of Cheng-Huang
|Draw an event card for each player and distribute them evenly.
|B03 |Goauldi Scouts
|Draw and place a sector.  Gain its value in gems.
|B04 |Quiet Prosperity
|Place a gem in each sector with exactly one disk.
|B05 |Genesis Device
|Place a gem in each blue-controlled sector.
|B06 |The Ruins of Loni City
|Take a gem from each unoccupied sector.
|B07 |Sustainable Farming
|Gain two gems.
|B08 |Xin Shield Formula
|While atop your discard: Disks may not be covered.
|B09 |Beta Theory
|When you sell this card, take a card from the market.
|B10 |The Living Ocean
|Place two gems in each explored, unoccupied sector.
|B11 |The Garthu Spaceport
|Reveal your hand.  Gain a gem for each different color revealed.
|B12 |Tidal Pools
|Move each non-blue top disk to the bottom of its stack.
|B13 |Jordani Current
|Gain a gem and shuffle the event deck.

|K01 |The Awakening
|Add a gem and a disk to an empty sector.
|K02 |Remembrance
|Put the bottom card of the event deck up for auction.
|K03 |Eldritch Theft
|Destroy a disk in the pool.
|K04 |The Altemian Purge
|Sell a card in the market for its value.
|K05 |Dark Ages
|Destroy all market cards.
|K06 |Event Horizon
|Destroy an empty sector.  This must not split the map.
|K07 |From the Dark
|Return a destroyed disk to any sector.
|K08 |Hanio's Resistance
|Move a disk to the bottom of its stack.
|K09 |The One True Path
|Gain a gem.  Retrieve this card.
|K10 |Stasis Pods
|While atop your discard: Disks cannot be removed by collapse.
|K11 |The Underground
|Gain a gem for each non-control black disk.
|K12 |Drakon's Escape
|Move a stack to an adjacent sector.
|K13 |Black Stars
|In final scoring: Destroyed black disks count for two influence.
|===
