= A History of Preascendant Humanity
Adam Blinkinsop <http://google.com/+AdamBlinkinsop>
1.0 RC1, {docdate}
:toc:
:homepage: http://blinks.github.io/ozymandias/

A game for two to four immortals, plays in about 500 millenia (an hour).

[verse, Percy Bysshe Shelley. Ozymandias]
____
And on the pedestal these words appear:
'My name is Ozymandias, king of kings:
Look on my works, ye Mighty, and despair!'
Nothing beside remains. Round the decay
Of that colossal wreck, boundless and bare
The lone and level sands stretch far away.
____

== Overview
You are immortal puppet-masters, managing a coalition of factions to ensure
they control the galaxy through exploration, expansion, exploitation, and
extermination of rival factions.  Not even the most powerful faction survives
forever, and the loyalty of currently-weak factions is cheap.  You must take
the long view.

== Objective
Have the most influence at the end of the game.

Colors are worth influence equal to the value of all sectors they control.
Each card is worth influence equal to its color.

.Card influence.
====
I have two red cards.

Red controls three hexes with values two, one, and zero, so my cards are worth
three influence each: six influence total.
====

== Components
- This rulebook.
- A deck of event cards.
- A collection of influence tokens.
- 24 control disks, six in each of four colors.
- 20 hexagonal sector tiles.

== Setup
- Shuffle the event deck.
- Draw four cards to make the *market*.
- Deal each player three cards and nine influence.
  - Players may *one-time only* return any number of cards to the bottom of the event
    deck and draw that many cards, as a mulligan. Shuffle the event deck after all
    players have had a chance to mulligan, if necessary.
- Decide which player is closest to immortality.  That player starts.

TODO(#3): A diagram of play.

== Parts of Play
The common play area is separated into the market and the galaxy. In addition, each
player has a hand and a discard pile.

=== The Market
Cards in the market can be put up for auction by players to expand the
range of powers wielded by the immortals.  At the end of each turn if the
market has fewer than four cards then add cards from the event deck until there are
four.

=== The Galaxy
The galaxy is defined by hexogonal sectors. At the start of the game the
universe is void and without form. Only through exploration does the universe
take shape.

Each sector has a value determined by its natural resources (the value on the
sector) and its invested influence (the amount of influence placed on the sector).
Only one color at a time may control a sector and it is the color that is on
top of the stack. A sector with no disks is *uncontrolled*.

.Sector control.
====
A sector contains a blue, white and red disk. Only the red disk, sitting on
top of the stack, has control of the sector.  The sector has an intrinsic value
of 2 and an additional point of influence for a total value of 3. Red has a
value of 3 and all other colors have 0.
====

== Play
Play proceeds in turns.  At the beginning of your turn, if you have no cards
in your hand, take your discard pile into your hand.  Take one of the following
actions:

- Auction a market card or any active card.
- Play a card for expansion.
- Play a card for its event.
- Reap a card from your hand for influence.

If there are no disks left in the pool at the end of your turn, *the game
ends.*

=== Auction
Put a card up for auction, either from the market ("seeding") or another
player's active card ("salting"). Place it in front of you, facing other players, during this process.
Everyone secretly bids influence and simultaneously reveals their bids.

The high bidder takes the card and gives the bid to:

- If from the market: the active player (if the active player would pay
   themselves, they pay the bank instead).
- If from a player: the former owner as compensation (if the card's
   owner would pay themselves, they pay the active player instead).

Losing bidders keep their bids.

Caveats:

- The active player breaks all ties.
- If nobody bids anything, the card is put on the bottom of the event deck.

=== Expand
Play a card to place a disk.

1. Put the card on your discard pile.  It's now active and the previous top card,
   if any, is inactive.
2. Take a disk of its color and place it on the map adjacent to another sector
   controlled by its color.  If no such sectors exist, place the disk in any
   unoccupied sector.
   - If you placed in an unexplored sector, draw a new sector to put there.
3. Collect influence equal to the sector's value.
4. If you drew a new sector, reveal and execute the top card of the event deck.
   (Leave it on top afterwards.)

=== Event
Play a card to execute its event.

1. Put the card on your discard pile.  It's now active and the previous top card,
   if any, is inactive.
2. Follow its instructions.

=== Reap
Sell a card for influence; place it in front of you sideways during this process.

1. Determine the value of its color by counting up sector values.
2. Collect that much influence from the bank.
3. Bid for preservation of that color.
4. Place the reaped card on the bottom of the market deck.

==== Preservation and Collapse

1. Everyone secretly bids influence and simultaneously reveals their bids.
2. Counter-clockwise from the active player, each bidder chooses which sectors
   to save.  Players can choose one sector for each influence they bid.
3. Destroy the top disk of each sector *not* saved.

.Preservation of blue
====
In a two-player game, blue controls two sectors.

Alice bids nothing and Bob bids one influence to preserve blue.

Bob decides which sector to save.  The other sector's top disk is destroyed.
====

== Game End
If all disks have been placed or destroyed, *the game ends.*

=== Scoring
1. Determine the value of each color by counting up sector values.
2. For every card in your hand or discard pile gain points equal to its color value.
3. Add the value of your influence.
4. The player with the highest combined card and influence value wins. In case of a tie the player with the most influence wins.

include::faq.asciidoc[]

include::cards.asciidoc[]
