= The Rise and Fall of Galactic Empires
Adam Blinkinsop <http://google.com/+AdamBlinkinsop>
0.17-{revision}, {docdate}
:toc: left
:homepage: http://blinks.github.io/ozymandias/

== Introduction

[verse, Percy Bysshe Shelley. Ozymandias]
____
And on the pedestal these words appear:
'My name is Ozymandias, king of kings:
Look on my works, ye Mighty, and despair!'
Nothing beside remains. Round the decay
Of that colossal wreck, boundless and bare
The lone and level sands stretch far away.
____

== Components
A complete set of _Rise_ includes:

* A deck of hexagonal sector tiles.
** Sectors start face-down in an _exploration_ pile, and are slowly added to
   the _galaxy map_ as players explore.  When destroyed, sectors are flipped
   face-down in-place.
** Each sector is considered controlled by a single color, or it is
   uncontrolled. A sector is considered controlled by a color if that color’s
   disk is on top of all other disks in the sector.
** http://printplaygames.com/product/die-cut-pieces-tiles-and-counters[P&P]:
   the 1.5" hex tiles, with three 0s and 4s, six 1s and 3s, and nine 2s.
* A deck of 56 cards.
** Cards start in a shuffled event _deck_, and are drawn out during
   exploration.
** Players each have two personal _discard_ piles.  A player's discard piles
   should be kept so each previous card's color is visible at all times.  The
   top card of both a player's discard piles are _active_, its icon showing
   when it will take effect.  When destroyed, cards are placed in a common
   _dead_ pile.
** The deck of cards represents archetypical historical events, the kind that
   get referenced in speech enough to become a stand-in for anything similar.
** Each card has a color of civilization that it influences, a title, and some
   rules text.
** http://www.printplaygames.com/product/blank-cards[P&P]: 14 each of black,
   white, blue, and red.
* 24 wooden empire disks.
** Empire disks start in a common _pool_ at the edge of the play area.  They're
   slowly moved onto the _galaxy map_ as players explore and conquer.  When
   disks are destroyed (or collapse), they're put back into the game box in a
   _dead_ pile.
** From https://www.printplaygames.com/product/25mm-x-7mm-wood-discs[P&P]: 6
   each of black, blue, red, and white.
* Resource tokens in two denominations: 50 1s, 50 5s.
** Resources start in a collective _bank_.  Players gain and spend resources,
   and resources are worth points at the end of the game.  A player's current
   resources should be visible at all times, except when bidding.
** From http://www.printplaygames.com/product/acrylic-gem-10mm[P&P]: clear for
   1s and red for 5s.
* This rule book.

== Set Up
. Shuffle the sector tiles and deal three to the center of the table to make
  the initial galaxy map.  They should be arranged in a triangle, so each is
  adjacent to the other two.
. Shuffle the deck of cards and deal two to each player.
. Give three resources to each player to make their initial banks.
. Place the decks, disks and resource tokens at the side of the table.

== Game Sequence
On your turn, you must *Explore*, *Conquer*, or *Reap*.  Play then proceeds
clockwise to the next player.  Endgame begins when all disks are gone from the
pool.

=== Explore

*Purpose*::
Discover new sectors and gain new cards.

*Procedure*::
. If there are less than three uncontrolled sectors in the galaxy, draw and
  place new sectors until there are three.
** Draw all sectors before you place any.
** While you do this, another player should deal each player three cards to
   make their exploration hand.
. Draft exploration hands.
** To draft, pick a card from your pack of three (or two, or one), and put the
   remaining cards between you and the player clockwise from you.
** If there are still cards between you, wait for that player to pick them up.
** Choose one with your picked card:
... Keep it: put it in your hand of cards, without revealing it.
... Consume it: put it in the dead pile, face up, and take resources.  If this
    was your first pick, take resources equal to the highest uncontrolled
    sector value.  If your second, the second highest.  If your third, the
    third highest.
... Trade it: put it on one of your discard piles, and put the rest of that
    pile in your hand.
. Pay one resource for each card in your hand.
** If you cannot (or refuse to) pay for a card, put it in the dead pile.

*Active Cards*::
Cards with an exploration effect give you other options for your pick.  If
multiple players want to use an effect at the same time, resolve them in play
order (starting with the active player).

.Explore example
====
TODO: first explore

TODO: a zero revealed

TODO: reshuffle?

TODO: no more sectors?
====

=== Conquer

*Purpose*::
Conquer a sector of the galaxy with a color in your hand.

*Procedure*::
. Put a card from your hand on one of your discard piles.
. Place a disk of that card's color on a sector tile.
.. Place the disk adjacent to a sector that color is already in (even if it
   doesn't control that sector).
.. If that color is nowhere in the galaxy, you may place it on any sector.
.. You may not place on a sector that color already controls.
. Gain resources equal to that sector's value.
. Each player (starting with you) may trigger an active card with a conquer
  effect that matches a color in that sector.
** Check for the color when your turn comes to trigger -- if disks have left
   the sector, you may not be able to trigger anymore.

*Active Cards*::
Cards with a conquer effect are the only way to act on someone else's conquer
action.

.Conquer example
====
TODO: if the last [color] disk is removed, future [color] events are canceled.
====

=== Reap

*Purpose*::
Destroy cards to gain resources.

*Procedure*::
. Place up to two cards from your hand face-down in front of you.
. Each other player may place a single card face-down.
.. If timing matters, these decisions happen in play order.
. Simultaneously reveal.  Each player takes resources equal to the sum of all
  sectors controlled by their card's color.
.. Set these cards aside to remember what colors were reaped.
. Starting with you, each player may resolve an active reap effect.  If nobody
  does, bid against collapse:
.. Count the total number of disks of all reaped colors in the galaxy, even if
   conquered -- this sum is the _Threshold_.
.. Each player secretly and simultaneously bids any amount of resources, then
   reveals.
.. If the total bid is at least the Threshold, pay all bids to the bank and end
   the turn. Otherwise, the difference is the number of disks to collapse:
... The high bidder removes that many disks from the top of any stacks or from
    the pool.  Disks must be a reaped color.
... If tied, those players take turns removing disks in play order.
.. Destroy all reaped cards.

.Reap example
====
TODO: card value computation, especially taller stacks.

TODO: threshold computation, especially conquered colors.
====

== Endgame
When all disks are gone from the pool, the endgame begins.  Players may not
explore or conquer, but must reap.  If your turn comes up and you have no cards
left to reap, the game ends.

The player with the most resources wins.

In the case of a tie, the player with the most cards left in hand wins.  If
still tied, the player who would take the next turn wins.

'''
include::faq.asciidoc[]

'''
include::cards.asciidoc[]
