= The Rise and Fall of Galactic Empires
Adam Blinkinsop <http://google.com/+AdamBlinkinsop>
0.19-{revision}, {docdate}
:toc: left
:homepage: http://blinks.github.io/ozymandias/

[verse, Percy Bysshe Shelley, Ozymandias]
____
And on the pedestal these words appear:
'My name is Ozymandias, king of kings:
Look on my works, ye Mighty, and despair!'
Nothing beside remains. Round the decay
Of that colossal wreck, boundless and bare
The lone and level sands stretch far away.
____

== Objective
*Rise* is played in turns.  Each turn, the active player chooses one of three
different actions, and everyone gets to take that action and possibly execute
one of their card effects.

You must influence and take advantage of shifting faction control to profit;
eliminating cards that are worthless while cycling cards that still have use.

*The winner is the player with the most resources at the end of the game.*

== Components
|===
|resources    |?? @ 1 and ?? @ 5.
|54 cards     |13 each in four factions.
|24 disks     |4 each in four factions.
|sector tiles |with a value from zero to four.
|===

== Setup
Shuffle the *sector tiles* and *deck of cards* separately.  Set the *resources*
and *disks* to one side, in common pools.

Give each player nine (9) resources and three cards, and draw and place a
sector to make the initial map.  Have each player draw and place a sector.

== Play
Rise is played over a number of turns.  On each turn, the active player chooses
an action with an associated bonus, then each player may act and optionally
resolve one of their cards that matches, then the active player completes the
action.  Turn passes clockwise to the next player, who chooses the next action.

=== The Actions
Each action grants the active player a special privilege, and also a specific
action that can be taken by _each_ player, in clockwise order, starting with
the active player.

Basic rules for all actions:

* Disks must be placed next to adjacent disks of their color if
  possible, or in any sector if there are no living disks of their color.
* If you cannot take an action, destroy a sector.

=== Explore (draw new cards)
. Draw and place new sectors until there are three uncontrolled, then draft
  (three cards each, picks go in hand or swap with discard).
. Each player may execute one active exploration effect.
. Place a disk in an uncontrolled sector.  Everyone pays that sector's value
  for each card in hand.

==== Notes
* With each card you pick in the draft, put it in your hand or swap it with one
  of your discard piles.
* If you cannot place a disk (either because none remain or no uncontrolled
  sectors exist or nothing's adjacent), destroy a sector.  Cards cost that
  sector's value.

=== Conquer (control a sector)
. Discard cards, place a disk, gain the sector's value in resources.
. Each player may execute one active exploration effect that matches a color in
  the conquered sector.

==== Notes
* Cards are discarded in packets -- a packet must include each conquered disk's
  color with the conquering disk's color on top.
* If (for example) two red disks are being conquered, the packet must include
  two red cards.
* If you cannot place a disk, destroy a sector.

=== Reap (turn cards into resources)
. Destroy any ruling disk, then everyone may sacrifice to gain resources.
. Each player may execute one active reap effect.
. Use sacrifices to collapse sectors.

==== Notes
* Each active card may be reaped at most once.
* Each sacrificed card reaps at most one active card.
* If you have an empty pile, a sacrifice gives resources equal to the total
  value of uncontrolled sectors.
* To collapse a sector, the active player must destroy a sacrificed card for
  each disk in the sector -- matching colors -- then destroy all disks in that
  sector.
* If no more sectors can be collapsed, destroy the remaining sacrificed cards.

== The End
The game ends _at the end of the turn_ in which all the disks are dead.

The player with the most resources is the winner!  If two or more players tie,
the player with the most cards in hand is the winner.  If still tied, the
player who would next take a turn wins.

== The Cards

For _all_ cards:

* When the deck runs out, shuffle the dead pile to make a new deck.
* When a card is on the top of a discard pile, it is considered _active._
* Only _active_ cards may be executed or reaped.

include::cards.asciidoc[]

'''
include::faq.asciidoc[]
