= The Rise and Fall of Galactic Empires
Adam Blinkinsop <http://google.com/+AdamBlinkinsop>
0.5-{revision}, {docdate}
:toc: left
:homepage: http://blinks.github.io/ozymandias/

== Introduction

[verse, Percy Bysshe Shelley. Ozymandias]
____
And on the pedestal these words appear:
'My name is Ozymandias, king of kings:
Look on my works, ye Mighty, and despair!'
Nothing beside remains. Round the decay
Of that colossal wreck, boundless and bare
The lone and level sands stretch far away.
____

_Rise_ is a 2- to 4-player board game depicting the life cycle of space-faring
civilizations over millennia.  Each player takes the role of a powerful
immortal seeking to have the most influence over humanity, whether benevolent
investment or malevolent destruction.

== Components
A complete set of _Rise_ includes:

* 22 hexagonal sector tiles.
* A deck of 52 cards, in four different colors.
* 24 black, blue, red, and white wooden disks.
* Power gems: white (1s) and red (5s).
* This rule book.

=== The Galaxy Map
The map is divided into hexagonal Sectors, each with a numeric value.  A sector
is a vast expanse of space arbitrarily reduced to a single number from zero to
four.

Each sector is considered Controlled by a single color, or it is uncontrolled.
A sector is considered Controlled by a color if that color's disk is on top of
all other disks in the sector.

.Sector control.
====
A sector with no disks on it is uncontrolled.

A sector with a single disk on it is controlled by that disk's color.

A sector with two or more disks on it is controlled by the top disk's color.
====

The stack of disks in a sector serves as a historical record of control in that
sector.  Civilizations that collapse reveal earlier disks, who retake control.

=== Cards
The deck of cards represents archetypical historical events, the kind that get
referenced in speech enough to become a stand-in for anything similar.  Each
card has a color of civilization that it influences, a title, and some rules
text.

.Sample card.
====
TODO: Insert a card image.
====

Cards may be played for one of two effects: Events or Expansion.  Cards may
also be Consumed for Power.

Players place cards on their own discard piles, recovering their discard in its
entirety when their hand is empty.  The top card of each player's discard pile
is considered "active".

Players will place cards in the market up for auction to expand the range of
powers their immortal avatars wield. Purchased cards will be placed in the
high-bidder's hand.  When consumed, cards will be buried on the bottom of the
deck.

=== Civilization Disks
Six wooden disks of each color represent archetypical civilizations.

At the beginning of the game, these have yet to rise to any real place in the
galaxy, and all sit in a pool at the side of the table.  Players move them from
the pool to the galaxy as civilizations expand.  Players take them from the
galaxy to their private banks as civilizations collapse.

A game of _Rise_ lasts only as long as there are disks in the common pool.  At
the end of the turn where the last civ is removed from the pool, the game ends.

== Set Up

. Shuffle the sector tiles and draw one to place in the middle of the playing
  area to make the initial explored sector.
. Shuffle the deck and place three face-up cards to the side of the playing
  area to make the initial market.
. Deal three more cards to each player to make their initial hands.  Players
  may look at their hands.  One time only, players may bury any number of
  cards and draw replacements from the deck.  If any player chooses this
  option, the deck should be reshuffled.
. Give nine influence to each player (four white gems and one red gem) to make
  their initial banks.  Place the rest near the market.
. Place the disks in a common pool reachable by all players.

== Game Sequence

A turn in _Rise_ begins with Dawn, followed by your Action.  If you have no
cards left in your hand, you may recover your discard pile before taking your
Action.

.Sustainable Farming
====
The card *Sustainable Farming* reads "Dawn: Gain two gems."

If this card is active (on top of your discard) when your turn begins, you gain
two gems before taking your action.  You only get two gems on your own turn.
====

At the end of your turn, if there are no disks left in the common pool, the
game ends.  Otherwise, refill the market.  Play proceeds clockwise to the next
player.

== Actions
There are four different actions you can take on your turn.  Each will move a
card from one place to another.  You may not forgo your turn by declining to
take an action, but you can choose to take an action that would have no
effect.

.Null expansion.
====
All the red disks have been placed by previous actions.  You may choose to
Expand with a red card in your hand, even though this will not cause a new disk
to be placed.
====

* *Expand* a color's control by discarding a card from your hand.
* *Invoke* an Event by discarding a card from your hand.
* *Auction* a market card or any player's active card.
* *Consume* a card from your hand for its value.

=== Expand
Discard a card to place a disk of its color.

==== Explore a new sector.
. Discard the card.
. Draw and place a new sector tile adjacent to any other sector tile.
. Place a disk of the card's color on that sector.
. If you placed a disk, resolve the exploration effect:
.. Reveal the top card of the deck and resolve its Event.
.. While resolving, the card is still considered the top card.

==== Conquer a controlled sector.
You may only do this adjacent to a sector that color already controls.  If the
color doesn't control any sectors, it may not conquer.

. Discard the card.
. Place a disk of the card's color on an explored sector.
. If you placed a disk, resolve the conquering effect:
.. Gain power equal to the conquered sector's value.
.. Resolve the event of one active or market card of the conquered sector's
   former color.

=== Invoke
Discard a card to resolve an "Event" effect.

. Discard the card.
. Resolve the "Event" effect on that card.

=== Auction
Place a card up for Auction to gain the high-bid or the card itself.

==== From the market.
. Choose any market card to put up for auction.  Place it in front of you,
  facing the other players.
. Secretly bid power from your bank, and simultaneously reveal with the other
  players (a first-price sealed-bid auction).
. The high-bidder Captures the card.  In the case of a tie, the active player
  chooses who Captures from the tied players.
.. Take their bid. If you Capture, pay the bank.
.. Put the card into their hand.
.. Resolve any Capture effects.

==== From a player.
. Choose any active card to put up for auction.  Place it in front of you,
  facing the other players.
. Secretly bid power from your bank, and simultaneously reveal with the other
  players (a first-price sealed-bid auction).
. The high-bidder Captures the card.  In the case of a tie, the active player
  chooses who Captures from the tied players.
.. Pay their bid to the card's former owner. If the former owner Captured, take
   their bid.
.. Put the card into their hand.
.. Resolve any Capture effects.

=== Consume
Bury a card to gain power.

. Place the consumed card on the table, sideways.
. Gain power equal to the sum of all sectors controlled by the card's color.
. Check for Collapse of sectors this color controls:
.. Hide your power and take zero or more into your hand as your bid.
.. When you’ve chosen your bid, hold your fist over the playing area.
.. Once all players have chosen, reveal your bids by opening your fists.
.. Sum the total power bid. Each power preserves one sector controlled by the
   Consumed color, starting with the highest value sector and continuing down.
.. If there is not enough power to preserve all that color’s sectors, pay all
   the power to the bank and destroy that color's active disk in sectors not
   preserved. In case of a tie, the active player chooses which to destroy.
   As always, give destroyed disks to the active player.
.. If there is more than enough, pay the power used to preserve to the bank and
   place the rest in any one sector controlled by the consumed color. (The
   active player chooses.)
. Resolve any Consume effects.
. Bury the consumed card on the bottom of the deck.

== Scoring and Victory
The object of the game is to score power.  Your cards and dead disks are each
worth power equal to the total value controlled by their color.  Power gems in
your bank also count towards your score.

TIP: Consuming cards locks in their color's value and gives you more power to
spend, but means you won't be able to score if it grows later.  It is best to
Consume a color at its peak.

.Scoring
====
Blue controls three sectors valued 2, 3, and 5.
Red controls one sector valued at 0.
White controls a sector valued at 3.

Alice holds sixteen power, three blue cards, a dead red disk, a white card and
a dead white disk.  Alice's blue cards score 30 power total (10 each), the red
disk scores nothing, and the white card and disk score 6 total.

Alice scores 52 power.
====

'''
include::faq.asciidoc[]

'''
include::cards.asciidoc[]
