= The Rise and Fall of Galactic Empires
Adam Blinkinsop <http://google.com/+AdamBlinkinsop>
0.22-{revision}, {docdate}
:toc: left
:homepage: http://blinks.github.io/ozymandias/

[verse, Percy Bysshe Shelley, Ozymandias]
____
And on the pedestal these words appear:
'My name is Ozymandias, king of kings:
Look on my works, ye Mighty, and despair!'
Nothing beside remains. Round the decay
Of that colossal wreck, boundless and bare
The lone and level sands stretch far away.
____

== Objective
*Rise* is played in turns.  Each turn, the active player chooses and resolves
one of three different actions.  Everyone then activates cards matching that
action.

You must influence and take advantage of shifting faction control to profit;
eliminating cards that are worthless while cycling cards that still have use.

*The winner is the player who holds the most valuable cards at the end of the game.*

== Components
|===
|resources    |?? @ 1 and ?? @ 5.
|60 cards     |15 each in four factions.
|24 disks     |6 each in four factions.
|sector tiles |with "terrain" types.
|===

== Setup
Shuffle the *sector tiles* and *deck of cards* separately.  Set the *resources*
and *disks* to one side, in common pools.

Give each player three cards, face-up to make their initial plots, and draw and
place three sectors (in a triangle) to make the initial map.

== Play
Rise is played over a number of turns.  On each turn, the active player chooses
an action, then each player may resolve at most one of their matching active
cards.

NOTE: I'm considering allowing players to discard in response to an action, to
set up their active cards.

At the beginning of your turn, you may recover one of your discard piles.

=== Explore (expand the galaxy and gain influence)
. [Optional] Draw and place a sector.
.. Discard all the cards in the horizon.
.. Refresh the horizon with new cards from the deck.
. Capture a card.
.. If from the horizon, pay its color's value.
.. If off the top of the deck, pay nothing.
. Each player may resolve one exploration effect.

A color's value is the product of the number of colors sacrificed to it + 1 and
the number of ruling disks it has.

=== Conquer (control sectors)
. Play one or more cards, either all different colors or all the same color.
.. You must place each card on a different pile.
.. You must place on existing piles before creating new piles.
. For each card, take a matching disk and a gem.
.. You must take unplaced disks before living disks.
.. You must take conquered disks before ruling disks.
.. You may not take dead disks.
. Place each disk on the corner of a sector.
.. You may place on an existing stack of disks.
.. You may not place on a stack that already contains the disk's color.
.. You may not create a stack only one edge away from another stack. (Catan)
. Each player may resolve one conquer effect.

=== Reap (consume empires and influence)
. Discard a card, and sacrifice one ruling disk to its color.
. Gain the discarded card's color's value.
. Each player may resolve one reap effect.

A color's value is the product of the number of colors sacrificed to it + 1 and
the number of ruling disks it has.

== The End
The game ends _at the end of the turn_ in which one of the following is true:

* No disks remain in the pool.
* All disks of one color are dead.

If the deck runs out, shuffle the discards into a new deck.

If the sectors run out, you can no longer refresh the horizon.

=== Scoring
Gems are points, nothing else matters.

include::cards.asciidoc[]

'''
include::faq.asciidoc[]
