application: xn--t-g9n
version: alpha
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /components
  static_dir: bower_components

- url: .*  # This regex directs all routes to main.app
  script: main.app

libraries:
- name: jinja2
  version: latest
